<a href="https://colab.research.google.com/github/Sundaypaul/PROJECTS/blob/main/CLIMATE_ANALYSIS_ASSIGNMENT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

CLIMATE ANALYSIS ASSIGNMENT SOLUTION
OGUNLEYE OLADAMOLA

In [ ]:
#Import drive
from google.colab import drive
drive.mount ('/content/drive')

Mounted at /content/drive


In [ ]:
#import libraries
import numpy as np
import pandas as pd

In [ ]:
#load the file
path = '/content/drive/MyDrive/climate_data.csv'
df = pd.read_csv(path)

In [ ]:
#checking out the first five rows
df.head()


Unnamed: 0  Year  Temperature (°C)  Precipitation (mm)
0           0  2010         17.483571           28.435078
1           1  2011         14.308678          104.104548
2           2  2012         18.238443           74.777003
3           3  2013         22.615149           42.744190
4           4  2014         13.829233          175.537406

In [ ]:
#converting the column Year to array
year = np.array(df['Year'])

In [ ]:
year

array([2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       2021, 2022, 2023])

In [ ]:
#converting the Temperature column to array
temp = np.array(df['Temperature (°C)'])

In [ ]:
temp

array([17.48357077, 14.30867849, 18.23844269, 22.61514928, 13.82923313,
       13.82931522, 22.89606408, 18.83717365, 12.65262807, 17.71280022,
       12.68291154, 12.67135123, 16.20981136,  5.43359878])

In [ ]:
#convert prep column to array
precipitation = np.array(df['Precipitation (mm)'])

In [ ]:
precipitation

array([ 28.43507835, 104.10454762,  74.77700329,  42.74418996,
       175.53740577,  42.09894894,  57.85905371, 220.02617378,
       100.52844807, 131.77413811, 164.93024789,  64.01373048,
       297.00600942,  53.51814463])

In [ ]:
#print out the arrays
print(year)
print(temp)
print(precipitation)

[2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 2023]
[17.48357077 14.30867849 18.23844269 22.61514928 13.82923313 13.82931522
 22.89606408 18.83717365 12.65262807 17.71280022 12.68291154 12.67135123
 16.20981136  5.43359878]
[ 28.43507835 104.10454762  74.77700329  42.74418996 175.53740577
  42.09894894  57.85905371 220.02617378 100.52844807 131.77413811
 164.93024789  64.01373048 297.00600942  53.51814463]


1. ANALYSE AVERAGE ANNUAL TEMPERATURE AND PRECIPITATION

In [ ]:
AVERAGE_TEMPERATURE = temp.mean()

In [ ]:

AVERAGE_TEMPERATURE
print(f'Average temperature is {AVERAGE_TEMPERATURE}')

Average temperature is 15.671480606254672


In [ ]:
AVERAGE_PRECIPITATION = precipitation.mean()

In [ ]:
AVERAGE_PRECIPITATION
print(f'Average precipitation is {AVERAGE_PRECIPITATION}')

Average precipitation is 111.2395085737263


2. IDENTIFY YEAR WITH EXTREME TEMPERATURE FLUCTUATIONS

In [ ]:
temp

array([17.48357077, 14.30867849, 18.23844269, 22.61514928, 13.82923313,
       13.82931522, 22.89606408, 18.83717365, 12.65262807, 17.71280022,
       12.68291154, 12.67135123, 16.20981136,  5.43359878])

In [ ]:
maximum_temp = temp.max()

In [ ]:
maximum_temp

22.896064077536955

In [ ]:
minimum_temp = temp.min()

In [ ]:
minimum_temp

5.43359877671101

In [ ]:
max_temp_year = year[np.argmax(temp)]
min_temp_year = year[np.argmin(temp)]

In [ ]:
print(f'Temperature peaked the highest in {max_temp_year} and was lowest in {min_temp_year}')

Temperature peaked the highest in 2016 and was lowest in 2023


3. calculate correlation between temperature and precipitation

In [ ]:
corr_temp_prep = np.corrcoef(temp, precipitation)

In [ ]:
corr_temp_prep

array([[1.00000000e+00, 9.86131867e-04],
       [9.86131867e-04, 1.00000000e+00]])

In [ ]:
corr_temp_prep_value = np.corrcoef(temp, precipitation)[1, 0]

In [ ]:
corr_temp_prep_value

0.0009861318670218262

4. Determine the trend of Climate change over the years

In [ ]:
slope, intercept = np.polyfit(year, temp, 1)
trend = f'temp = {slope: .4f} * year + {intercept: .4f}'
print(trend)
print(f'To find the temp of any year, use the fomular {trend}')

temp = -0.5352 * year +  1094.9988
To find the temp of any year, use the fomular temp = -0.5352 * year +  1094.9988


# QUESTION TWO

In [ ]:
#load the file
path = '/content/drive/MyDrive/Dataset/student_scores.csv'
df2 = pd.read_csv(path)

In [ ]:
df2.head()

Unnamed: 0  Mathematics  Physics  Chemistry  Computer Science  \
0         John Doe           78       91         68                54   
1       Jane Smith           58       62         50                50   
2  Michael Johnson           61       92         41                63   
3      Emily Davis           72       51         97                61   
4      Chris Brown           81       67         99                55   

   Biology  History  English Literature  Psychology  Art History  Statistics  
0       82       47                 100          60           78          97  
1       63       92                  75          79           63          42  
2       83       69                  77          41           99          60  
3      100       83                  64          88           66          98  
4       54       86                  90          83           94          91

In [ ]:
df2.value_counts()

Unnamed: 0         Mathematics  Physics  Chemistry  Computer Science  Biology  History  English Literature  Psychology  Art History  Statistics
Angela Thompson    100          71       43         69                76       62       78                  84          54           82            1
Charles Martin     54           65       81         99                52       90       71                  78          88           91            1
Susan Harris       42           40       44         65                94       53       78                  66          48           54            1
Sarah Rodriguez    93           68       57         65                83       73       49                  75          53           70            1
Robert Thomas      84           80       68         54                84       40       64                  46          48           63            1
Michael Johnson    61           92       41         63                83       69       77                  41          99           60            1
Linda Hernandez    40           83       47         63                50       90       56                  47          74           74            1
Laura Martinez     67           86       99         46                83       100      47                  86          74           53            1
Karen Anderson     84           57       86         92                63       65       64                  99          99           99            1
Joseph White       83           79       61         66                74       40       74                  76          86           53            1
John Doe           78           91       68         54                82       47       100                 60          78           97            1
Jessica Wilson     96           42       76         90                46       60       48                  78          57           43            1
Jane Smith         58           62       50         50                63       92       75                  79          63           42            1
James Taylor       87           54       47         53                62       99       96                  79          60           55            1
Emily Davis        72           51       97         61                100      83       64                  88          66           98            1
Elizabeth Jackson  47           51       73         72                87       94       62                  63          76           74            1
David Garcia       56           75       89         79                43       41       45                  93          81           43            1
Daniel Lee         64           99       53         89                97       48       65                  92          41           59            1
Chris Brown        81           67       99         55                54       86       90                  83          94           91            1
William Moore      72           98       44         81                78       97       80                  67          46           48            1
Name: count, dtype: int64

In [ ]:
df2.nunique()

Unnamed: 0            20
Mathematics           18
Physics               19
Chemistry             16
Computer Science      17
Biology               17
History               18
English Literature    17
Psychology            18
Art History           17
Statistics            16
dtype: int64

In [ ]:
#convert to numpy array
df2.to_numpy()

array([['John Doe', 78, 91, 68, 54, 82, 47, 100, 60, 78, 97],
       ['Jane Smith', 58, 62, 50, 50, 63, 92, 75, 79, 63, 42],
       ['Michael Johnson', 61, 92, 41, 63, 83, 69, 77, 41, 99, 60],
       ['Emily Davis', 72, 51, 97, 61, 100, 83, 64, 88, 66, 98],
       ['Chris Brown', 81, 67, 99, 55, 54, 86, 90, 83, 94, 91],
       ['Jessica Wilson', 96, 42, 76, 90, 46, 60, 48, 78, 57, 43],
       ['Daniel Lee', 64, 99, 53, 89, 97, 48, 65, 92, 41, 59],
       ['Laura Martinez', 67, 86, 99, 46, 83, 100, 47, 86, 74, 53],
       ['David Garcia', 56, 75, 89, 79, 43, 41, 45, 93, 81, 43],
       ['Sarah Rodriguez', 93, 68, 57, 65, 83, 73, 49, 75, 53, 70],
       ['James Taylor', 87, 54, 47, 53, 62, 99, 96, 79, 60, 55],
       ['Karen Anderson', 84, 57, 86, 92, 63, 65, 64, 99, 99, 99],
       ['Robert Thomas', 84, 80, 68, 54, 84, 40, 64, 46, 48, 63],
       ['Linda Hernandez', 40, 83, 47, 63, 50, 90, 56, 47, 74, 74],
       ['William Moore', 72, 98, 44, 81, 78, 97, 80, 67, 46, 48],
       ['Elizab

In [ ]:
scores = df2.drop(columns = 'Unnamed: 0')

In [ ]:
#1. Find the average scores for each students
average_per_student = np.mean(scores, axis=1)
df2['Average Score'] = average_per_student
print("Overall Average Score for Each Student:")
print(df2[['Unnamed: 0', 'Average Score']])


Overall Average Score for Each Student:
           Unnamed: 0  Average Score
0            John Doe           75.5
1          Jane Smith           63.4
2     Michael Johnson           68.6
3         Emily Davis           78.0
4         Chris Brown           80.0
5      Jessica Wilson           63.6
6          Daniel Lee           70.7
7      Laura Martinez           74.1
8        David Garcia           64.5
9     Sarah Rodriguez           68.6
10       James Taylor           69.2
11     Karen Anderson           80.8
12      Robert Thomas           63.1
13    Linda Hernandez           62.4
14      William Moore           71.1
15  Elizabeth Jackson           69.9
16       Joseph White           69.2
17       Susan Harris           58.4
18     Charles Martin           76.9
19    Angela Thompson           71.9


In [ ]:
# 2. Average Score per Course
average_per_course = np.mean(scores, axis=0)
print("\nAverage Score per Course:")
print(dict(zip(scores.columns, average_per_course)))


Average Score per Course:
{'Mathematics': 70.95, 'Physics': 70.55, 'Chemistry': 66.15, 'Computer Science': 68.3, 'Biology': 72.7, 'History': 71.45, 'English Literature': 69.15, 'Psychology': 74.0, 'Art History': 69.25, 'Statistics': 67.45}


In [ ]:
# 3. Highest and Lowest Performing Students
highest_score_idx = np.argmax(average_per_student )
lowest_score_idx = np.argmin(average_per_student )

highest_performer = df2.iloc[highest_score_idx]
lowest_performer = df2.iloc[lowest_score_idx]

print("\nHighest Performing Student:")
print(f"{highest_performer['Unnamed: 0']} with an average score of {highest_performer['Average Score']}")

print("\nLowest Performing Student:")
print(f"{lowest_performer['Unnamed: 0']} with an average score of {lowest_performer['Average Score']}")



Highest Performing Student:
Karen Anderson with an average score of 80.8

Lowest Performing Student:
Susan Harris with an average score of 58.4


In [ ]:
# 4. Pass Rate (students who scored above 50 in all subjects)
pass_mask = np.all(scores > 50, axis=1)
pass_rate = np.sum(pass_mask) / len(pass_mask) * 100
print(f"\nPass Rate: {pass_rate:.2f}%")


Pass Rate: 20.00%


In [ ]:
# 5. Variability in Courses (Standard Deviation)
std_per_course = np.std(scores, axis=0)
print("\nStandard Deviation (Variability) per Course:")
print(dict(zip(scores.columns, std_per_course)))


Standard Deviation (Variability) per Course:
{'Mathematics': 17.41400298610288, 'Physics': 17.477056388305215, 'Chemistry': 19.779471681518693, 'Computer Science': 14.970303938130314, 'Biology': 16.967910890855126, 'History': 21.041566006359886, 'English Literature': 15.41517109862878, 'Psychology': 15.732132722552274, 'Art History': 17.80975856096876, 'Statistics': 19.153263429504648}
